#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := esp32-srp-test
EXTRA_COMPONENT_DIRS := $(abspath ./../)
#CFLAGS := -D_SRP_TEST_VECTOR

include $(IDF_PATH)/make/project.mk


